import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { calculateDemandRecommendation } from "../../../server/domain/demand-forecast-policy";

const initialOrders = [
  { id: "PO-DEMO-104", supplier: "مورد اصطناعي معتمد", product: "باراسيتامول 500 مجم", batch: "DEMO-B24", status: "قيد الاستلام", eta: "2026-08-18", qty: 100, received: 80, risk: "فرق استلام" },
  { id: "PO-DEMO-105", supplier: "مورد اصطناعي معتمد", product: "قفازات فحص", batch: "DEMO-G11", status: "معتمد", eta: "2026-08-22", qty: 500, received: 0, risk: "طبيعي" },
  { id: "PO-DEMO-106", supplier: "مورد اصطناعي معتمد", product: "محلول تعقيم", batch: "DEMO-S07", status: "محجور", eta: "2026-08-16", qty: 60, received: 60, risk: "حجر جودة" },
];

const demoForecasts = [
  { id: "MED-1", product: "باراسيتامول 500 مجم", history: [10, 12, 8, 11, 9, 10, 12, 11, 13, 10, 9, 12, 11, 10], onHand: 20, open: 5, lead: 3, review: 2, service: "high" as const, shelf: 120 },
  { id: "SUP-2", product: "قفازات فحص", history: [52, 48, 55, 50, 61, 57, 54, 49, 58, 53, 56, 60, 51, 55], onHand: 430, open: 500, lead: 7, review: 7, service: "standard" as const, shelf: null },
  { id: "COS-3", product: "محلول تعقيم", history: [4, 6, 3], onHand: 8, open: 0, lead: 5, review: 3, service: "critical" as const, shelf: 6 },
];

type SupplyChainWorkspaceProps = { branchId?: number | null; jurisdictionId?: number | null; demo?: boolean };

export function SupplyChainWorkspace({ branchId = null, jurisdictionId = null, demo = true }: SupplyChainWorkspaceProps) {
  const [orders, setOrders] = useState(initialOrders);
  const [query, setQuery] = useState("");
  const historyQuery = trpc.erp.forecast.salesHistory.useQuery(branchId && jurisdictionId && !demo ? { branchId, jurisdictionId, historyDays: 56 } : { branchId: 1, jurisdictionId: 1, historyDays: 56 }, { enabled: Boolean(branchId && jurisdictionId && !demo), retry: false });
  const filtered = useMemo(() => orders.filter(order => `${order.id} ${order.supplier} ${order.product} ${order.batch}`.toLowerCase().includes(query.toLowerCase())), [orders, query]);
  const recommendations = useMemo(() => {
    if (demo) return demoForecasts.map(item => ({ item, result: calculateDemandRecommendation({ scope: { organizationId: 1, branchId: 10, jurisdictionId: 20 }, productId: item.id, dailyUnits: item.history, onHand: item.onHand, openOrderUnits: item.open, leadTimeDays: item.lead, reviewPeriodDays: item.review, serviceLevel: item.service, shelfLifeDays: item.shelf }) }));
    return (historyQuery.data ?? []).map(item => ({ item: { id: String(item.productId), product: `الصنف #${item.productId}`, history: item.historyDays, onHand: 0, open: 0, lead: 7, review: 7, service: "standard" as const, shelf: null }, result: calculateDemandRecommendation({ scope: item.scope, productId: String(item.productId), dailyUnits: item.historyDays, onHand: 0, openOrderUnits: 0, leadTimeDays: 7, reviewPeriodDays: 7, serviceLevel: "standard", shelfLifeDays: null }) }))
  }, [demo, historyQuery.data]);
  const simulateReceive = (id: string) => setOrders(current => current.map(order => order.id === id ? { ...order, status: "تم الاستلام — بانتظار المطابقة", received: order.qty, risk: "طبيعي" } : order));
  const simulateQuarantine = (id: string) => setOrders(current => current.map(order => order.id === id ? { ...order, status: "محجور", risk: "حجر جودة" } : order));
  return <div className="space-y-5" dir="rtl">
    <div className="grid gap-3 md:grid-cols-4"><Metric title="أوامر مفتوحة" value={String(orders.filter(order => !["محجور", "تم الاستلام — بانتظار المطابقة"].includes(order.status)).length)} /><Metric title="فرق استلام" value={String(orders.filter(order => order.risk === "فرق استلام").length)} tone="amber" /><Metric title="حالات حجر" value={String(orders.filter(order => order.status === "محجور").length)} tone="rose" /><Metric title="توصيات إعادة الطلب" value={String(recommendations.filter(({ result }) => (result.suggestedOrderUnits ?? 0) > 0).length)} tone="emerald" /></div>
    <Card><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-3"><span>لوحة توقع الطلب وإعادة الطلب</span><Badge variant="outline">{demo ? "وضع العرض — بيانات اصطناعية" : "بيانات مبيعات خادمية ضمن النطاق"}</Badge></CardTitle><p className="text-sm leading-6 text-slate-500">توصيات قابلة للتفسير مبنية على سجل الاستهلاك المتاح، والمهلة، وفترة المراجعة، ومخزون الأمان، والطلبات المفتوحة. لا يتم إنشاء أمر شراء تلقائياً.</p></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-3">{recommendations.map(({ item, result }) => <div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{item.product}</p><p className="mt-1 text-xs text-slate-500">المهلة {item.lead} أيام · المراجعة {item.review} أيام</p></div><Badge variant="outline" className={result.dataQuality === "insufficient" ? "border-rose-300 text-rose-700" : result.dataQuality === "limited" ? "border-amber-300 text-amber-700" : "border-emerald-300 text-emerald-700"}>{result.dataQuality === "insufficient" ? "بيانات غير كافية" : result.dataQuality === "limited" ? "بيانات محدودة" : "بيانات كافية"}</Badge></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Stat label="توقع يومي" value={result.forecastDailyUnits === null ? "—" : `${result.forecastDailyUnits} وحدة`} /><Stat label="مخزون الأمان" value={result.safetyStockUnits === null ? "—" : `${result.safetyStockUnits} وحدة`} /><Stat label="نقطة الطلب" value={result.reorderPointUnits === null ? "—" : `${result.reorderPointUnits} وحدة`} /><Stat label="المقترح" value={result.suggestedOrderUnits === null ? "مراجعة يدوية" : `${result.suggestedOrderUnits} وحدة`} emphasis={(result.suggestedOrderUnits ?? 0) > 0} /></div><details className="mt-4 text-xs text-slate-600"><summary className="cursor-pointer font-medium">كيف حُسبت التوصية؟</summary><div className="mt-2 space-y-1 leading-5">{result.explanation.map(line => <p key={line}>{line}</p>)}</div></details></div>)}</div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">{demo ? "التوصيات اصطناعية ولا تنشئ حركة تشغيلية." : "تم جلب التاريخ من المبيعات المسجلة ضمن الفرع والاختصاص المؤكدين. بيانات المخزون والطلبات المفتوحة غير متاحة لهذا العرض، لذلك لا تُعتبر التوصية أمر شراء."} التوصية أداة دعم قرار فقط، وتتطلب مراجعة واعتماد مسؤول مخزون مخوّل، ولا تتجاوز FEFO أو الصلاحية أو القيود التنظيمية.</p></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-3"><span>متابعة سلاسل الإمداد والتوريد</span><Badge variant="outline">{demo ? "بيانات اصطناعية — لا إرسال لمورد" : "سجل تشغيلي للعرض فقط"}</Badge></CardTitle><p className="text-sm leading-6 text-slate-500">تتبع أمر الشراء من الاعتماد إلى الشحن والاستلام والمطابقة والحجر والاستدعاء، مع ربط كل حدث بالمؤسسة والفرع والاختصاص وسجل التدقيق.</p></CardHeader><CardContent><div className="mb-4 flex items-center gap-2"><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث برقم الأمر أو المورد أو المنتج أو الدفعة" aria-label="بحث سلسلة الإمداد" /></div><div className="space-y-3">{filtered.map(order => <div key={order.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{order.id} · {order.product}</p><p className="mt-1 text-xs text-slate-500">{order.supplier} · الدفعة {order.batch} · موعد متوقع {order.eta}</p></div><Badge variant="outline" className={order.risk === "حجر جودة" ? "border-rose-300 text-rose-700" : order.risk === "فرق استلام" ? "border-amber-300 text-amber-700" : "border-emerald-300 text-emerald-700"}>{order.risk}</Badge></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><span>الحالة: <strong>{order.status}</strong></span><span>الكمية: {order.received} / {order.qty}</span><span>المسار: اعتماد ← شحن ← استلام ← مطابقة</span></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => simulateReceive(order.id)} disabled={order.status === "محجور"}>محاكاة الاستلام والمطابقة</Button><Button size="sm" variant="outline" onClick={() => simulateQuarantine(order.id)}>محاكاة الحجر</Button></div></div>)}{filtered.length === 0 && <p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">{demo ? "لا توجد نتائج في السجل الاصطناعي." : "لا توجد بيانات مبيعات مسجلة ضمن النطاق المحدد."}</p>}</div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">التكامل الحقيقي مع الموردين وEDI/GS1 والجهات التنظيمية يحتاج مواصفات واعتمادات وبيئة اختبار رسمية؛ لن تُنشأ أوامر شراء أو حركات مخزون فعلية من هذا العرض.</p></CardContent></Card>
  </div>;
}
function Stat({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div className={`rounded-xl p-3 ${emphasis ? "bg-cyan-50 text-cyan-900" : "bg-slate-50 text-slate-700"}`}><p className="text-xs opacity-70">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Metric({ title, value, tone = "cyan" }: { title: string; value: string; tone?: "cyan" | "amber" | "rose" | "emerald" }) { const tones = { cyan: "bg-cyan-50 text-cyan-800", amber: "bg-amber-50 text-amber-800", rose: "bg-rose-50 text-rose-800", emerald: "bg-emerald-50 text-emerald-800" }; return <div className={`rounded-2xl p-4 ${tones[tone]}`}><p className="text-xs opacity-75">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
